### ISSUE TITLE
Interested in the project

### ISSUE THREAD

**Issue by Denisolt** [BelalC/sign2text#1]
Hi, 
Have you finished the project or you are still working on it?

**Comment by BelalC** [comment]
Hey Deni - I still have plans for the project, but I'm not working on it right now. Would welcome collaborators though! Did you have any ideas for it?

Belal

**Comment by Denisolt** [comment]
I have just started on Deep Learning, therefore I am lacking a lot of knowledge. Currently working on Ceizure Detection using Deep Learning. I wanted to look into this as a side project. I would love to help if I can, especially if you could help me learn as well. Do you want to move the chat somewhere else? email, telegram (if you have it) ?

thank you!

**Comment by BelalC** [comment]
Sounds good! drop me a msg at belalc80@gmail.com <mailto:belalc80@gmail.com>
