### ISSUE TITLE
Questions on running demo

### ISSUE THREAD

**Issue by joohaeng** [BelalC/sign2text#3]
@BelalC, Thank you for sharing interesting project. I have some questions on running the demo:

1. what should be the recommend camera resolution?

2. Should my hand be placed inside the rectangle?

3. Does a background affect the result? Should it be a clean wall or similar?

Demo is literally running, but not showing some intelligence, yet. How can I expect the recognition rate in real experiment?

**Comment by BelalC** [comment]
@joohaeng 

1 - I was running it on my MacBook Pro (Retina, 15-inch, Mid 2014) which has a 720p FaceTime HD camera. Anything comparable should be fine!

2 - Yes, the rectangle is cropped and classified

3 - Yes, currently the system only works on a plain matte background (ideally white) under good lighting conditions. I am planning to make the system more robust so it can deal with more complex backgrounds + lighting conditions. Updates to come in the next few weeks hopefully. From my experiments in 'real life', there are perhaps 9-10 letters which it classifies with almost 100% accuracy (try A, B, C, O, U, V, W), others at around 80-90% accuracy and a few others which can be tricky. 

Let me know how you get on!
