### ISSUE TITLE
Running command

### ISSUE THREAD

**Issue by joohaeng** [BelalC/sign2text#4]
@BelalC, When running the demo, I specify the name of the pre-trained net using "-m" option. But, I could not make it work using "-weights" option. Is it related to the files in "weights" folder? Could you give some working example?

**Comment by BelalC** [comment]
@joohaeng  - yes the '-w' argument is for specifying what weights you want to load into the model. By default, the model will load the pre-trained weights I included in the 'weights' folder. You only need to specify the weights argument if you want to load your own pre-trained weights. Example using weights included in repo:

`python live_demo.py -m vgg16`

**Comment by joohaeng** [comment]
@BelalC Thanks! By the way, which pre-trained net shows the best performance?

**Comment by BelalC** [comment]
VGG16 was the most accurate the last time I tested it out, but it's fairly compute heavy. MobileNet was the fastest but least accurate, although it could definitely be improved with some more tweaking + data. Let me know how you go!
