### ISSUE TITLE
[Feature Request] Gesture controller support

### ISSUE THREAD

**Issue by a7nair** [BelalC/sign2text#7]
Hey there,
So I've been looking into sign language conversion solutions to help a friend of mine. This is a great solution & I was wondering if this application could be integrated with a gesture controller like the KAI ( https://vicara.co ).
This would allow for a more portable solution that my friend could use even without a laptop.
Please let me know if this would be possible.

**Comment by BelalC** [comment]
Hi! Thanks for sharing the link, yes that could be possible although I haven’t used the vicara device before. Would alphabet translation be useful for your friend?

Belal
